### ISSUE TITLE
Main window Size should not be a mandatory parameter

### ISSUE THREAD

**Issue by AdrianDAlessandro** [ImperialCollegeLondon/guikit#51]
Include a default value in the constructor for `core.MainApp`

**Comment by srikanthravipati** [comment]
Is not it already there? or am I missing something else?https://github.com/ImperialCollegeLondon/guikit/blob/c9bd33f61da4e7336b055f1a4d659fa10c73a504/guikit/scripts.py#L40-L42 (see #44)

**Comment by AdrianDAlessandro** [comment]
> Is not it already there? or am I missing something else?

I was referring to the constructor for `MainApp`. If a program doesn't use the in-built `run()` method that you've referenced, then it will fail to launch unless they provide the `size_mainwindow` parameter.
https://github.com/ImperialCollegeLondon/guikit/blob/c9bd33f61da4e7336b055f1a4d659fa10c73a504/guikit/core.py#L211-L221
