### ISSUE TITLE
Add tests for new functionality

### ISSUE THREAD

**Issue by alexdewar** [ImperialCollegeLondon/guikit#62]
As discussed with @dalonsoa, there are currently no tests for the two fixes I just implemented.

**Comment by alexdewar** [comment]
Ok, so it seems like this might be harder than I anticipated :laughing: 

Using the current mocking setup, it seems like ``run_thread()`` won't actually start a new thread, so I'm guessing I maybe need to mock up a dummy ``wx.Window`` to pass to ``ThreadPool``...? Not sure what the best approach is here, because ideally I'd like to start a ``ThreadPool`` at the start of a test and terminate it properly at the end of it.

**Comment by dalonsoa** [comment]
Could you share in a draft PR what you have so far? We are writing - at least for now - unit tests, not functional tests, meaning that there's likely a lot of mocking needed.

**Comment by alexdewar** [comment]
What I have currently is a non-working mess, but I'll try to bash it into some kind of reviewable shape. It's probably easier to talk about actual code!
