### ISSUE TITLE
Add option to not synchronise threads with GUI thread

### ISSUE THREAD

**Issue by alexdewar** [ImperialCollegeLondon/guikit#64]
So it turns out the use case I had in mind for iPANACEA won't actually work with guikit
as it stands anyhow. D'oh!

The problem I have is that we *need* data acquisition and the writing of that data to
disk to happen on the same thread, otherwise at best the data will be written in a
non-deterministic order and at worst data corruption will happen and you'll get a load
of binary crud in your CSV file.

I still think this is a general enough problem that it should be solved within guikit.
We still want the data acquisition thread to be started/stopped when the window is
opened/closed.

**Comment by dalonsoa** [comment]
Could you clarify why data will be written in a non-deterministic order? There should be only one thread saving data to disk, and not opening a new thread every time there is data, so I don't see how it is possible that the order the data is saved will not follow the order in which it is produced.

**Comment by alexdewar** [comment]
After probing around a bit I think the problem is a bit more subtle than I thought here.

I changed iPANACEA to use the ``guikit`` thread API for data acquisition, but when I record data using the program I get things like this:
```
Timestamp,CH0,CH1,CH2,CH3,CH4,CH5,CH6,CH7,CH8,CH9,CH10,CH11,CH12,CH13,CH14,CH15,CH16,CH17,CH18,CH19,CH20,CH21,CH22,CH23
18.307315731000017,-17.620167,-11.330302,1.7206335,7.5569935,-11.135593,-9.8764,-2.186346,-15.292825,11.199072,18.257393,11.774041,-7.7480392,-5.460982,-2.1027253,14.247261,11.565905,9.6115,8.4029665,3.3710744,0.039674062,-6.405225,9.552904,-2.9639575,-19.091158
17.688978042999224,16.39027,-15.518052,-10.505081,6.004822,4.7035127,4.752342,9.9417095,2.797937,12.134769,-1.5887936,18.518631,6.560259,1.3446455,10.361034,6.079287,-6.946013,-4.4508195,-5.795465,-19.273048,8.04651,-19.598988,16.542864,6.6243477,2.354808
17.703542139999627,17.399212,16.557512,-15.890987,-8.002563,11.777093,-15.790887,12.076174,-12.602313,16.04236,-9.589526,17.19718,-10.5630665,18.333078,-17.42668,16.864529,-15.381329,6.126896,-19.650257,13.299356,13.565477,6.5779595,-10.924406,13.769341,-4.8451185
18.075045470000077,-3.2190924,12.965484,-19.871212,3.930784,-1.8231758,19.19126,5.149083,-10.935392,15.760979,-5.6758323,5.0477614,-15.994141,-19.45616,10.450148,18.874477,-3.7543871,-0.9027375,2.5434127,-4.8402357,-2.677694,10.669881,7.625355,17.123936,-2.545854```

The process we're using looks like this:

1. A file is opened for writing and passed to a ``DataRecorder`` object
2. Data is read continually on the data acquisition thread and this is broadcast via the ``panacea.data_acquired`` message
3. A ``DataRecorder`` object receives the message and writes this data to the CSV file

For the working version of iPANACEA, 2 and 3 run on the same thread, so new data is not read on the data acquisition thread until previous data has been written. What must be happening with the broken version is that the actual writing is happening on a separate thread somehow. It's a head scratcher!

If you want to look at how I implemented the not-working version, I've pushed it here: https://github.com/ImperialCollegeLondon/iPANACEA/commit/bd96dc7effd96ea0a7a4b57c095fa1638b377c30

The only thing I can think of is that maybe it's something to do with the ``post_event()`` business happening here: https://github.com/ImperialCollegeLondon/guikit/blob/547a7150704bdce1a92ce7c0c1081407ff9e5c54/guikit/threads.py#L70

**Comment by alexdewar** [comment]
> I've left a couple of comments on the commit you mention. Now, I don't see anything that could make 2 and 3 run in separate threads considering the current implementation. So, all looks OK to me. The `post_event` plays no role as that is only called after the threaded function (`_run_thread` in this case) returns.

Hmm, this is v strange then.

> 
> BTW, what's exactly wrong with the measured data you show above?

The timestamps are out of order, meaning the writing is not happening synchronously. There is also some outright data corruption (i.e. binary crud in the file) that I didn't show, which I suspect is due to non-thread-safe calls to some Python function or other.

**Comment by alexdewar** [comment]
Ok it turns out that this had nothing to do with ``guikit`` and everything to do with my crummy downstream code :wink:. It turns out I was calling ``start_thread()`` a bunch of times by accident and that was what was causing the problem.
