### ISSUE TITLE
Use a third-party lib for figuring out where log files should go

### ISSUE THREAD

**Issue by alexdewar** [ImperialCollegeLondon/guikit#70]
At present, ``guikit`` makes a fairly sensible decision on where log files should go based on the platform:
```py
if sys.platform == "win32":
    path = Path.home() / "AppData" / "Local" / app_name
elif sys.platform == "darwin":
    path = Path.home() / "Library" / "Application Support" / app_name
else:
    path = Path.home() / f".{app_name}"
```

As it turns out though correctly divining the app's data path correctly in all cases is surprisingly subtle and finicky. On Windows, for example, it is apparently affected by user settings, locale, environment variables etc. and it seems like the only reliable way to get it is to query some Windows API or other. On Linux, while ``~/.my_app`` isn't a *terrible* place to put app data, it is a bit old-school: nowadays apps tend to use [the XDG specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) instead.

There is a great Python package for this called [platformdirs](https://pypi.org/project/platformdirs/) which handles all this low level jiggery-pokey, so you can just do:
```
>>> import platformdirs
>>> platformdirs.user_log_dir('ipanacea')
'/home/alex/.cache/ipanacea/log'
```

What do you think, @dalonsoa? Happy to implement this if desired.

**Comment by dalonsoa** [comment]
Looks good to me! Anything that is about re-using existing solutions is good!

Happy for you to take on this... but not know. Leave it for Hacktoberfest!

**Comment by alexdewar** [comment]
Just a thought, but perhaps we could add a Hacktoberfest tag to issues like this so we can find them again?

**Comment by dalonsoa** [comment]
Mentioning this in my ToDo list for the next team meeting :)
